org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

kotlin.stdlib.default.dependency=false
org.gradle.configuration-cache=true
org.gradle.caching=true

groupId=alfredabdo.ide.plugins
pluginId=alfredabdo.ide.plugins.translations
pluginVersion=0.1.0-alpha08